# Generated by Django 5.2 on 2025-04-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=10, unique=True, verbose_name=10)),
                ('name', models.CharField(max_length=10)),
                ('gender', models.IntegerField(choices=[(1, '男'), (0, '女')])),
                ('email', models.EmailField(max_length=50, null=True)),
                ('password', models.CharField(default='1', max_length=20)),
            ],
        ),
    ]
